import streamlit as st
import streamlit.components.v1 as components
def app():
    st.title("List of EVER-AI Products")
    st.header("Health Dashboard")
    st.write("Our health dashboard is a tool that provides monitor performance, patient volume, areas of growth, and revenue for 4 cities in Thailand.")
    st.header("Predictive Health")
    st.write("Our predictive health system can be forecasted or identified patients who may at high risk for developing diseases in the future.")
    st.header("Diagnosis Prediction based on Clinical Text")
    st.write("The purpose of this system is to screen the patient’s symptoms and identify the disease as well as department for the screening centre for hospital.")
    st.header("Drug Recommendation System")
    st.write("We would like to help doctor recommending drug based on diagnose, patient’s health profiles, lifestyle, and habits.")
    st.header('Drug Interaction')
    st.write("Drug interaction system is a tool to identify which drugs and foods that patient should be avoid.")
    st.header('Outbreak Forecasting')
    st.write("Outbreak forecasting system is a tool to predict the number of patients in next 30 days and so on.")
    st.header('Outbreak Map')
    st.write("It is a visualization tool to identify the area and number of patients by map.")
    st.header('Parkinson Drawing Prediction')
    st.write("This system can be help to classify a person who can be risked to Parkinson’s disease from drawing image.")
    st.header('OCR (Image / Handwriting to Text)')
    st.write("We would to like to reduce input time for the registration department by converting image to text, i.g. ID card, alien card, and passport with Optical Character Recognition (OCR) system. Also, it can be classified  the document form and its section.")
    st.header('Speech Recognition')
    st.write("We develop text-to-speech and speech-to-text system for taking time to write or type out notes by speak aloud for user in hospital.")
    st.header('Chest X-ray Classification')
    st.write("Chest x-ray classification system can help to classify diseases from x-ray film.")
    st.header('CCTV Detection')
    st.write("We aim to detect images from CCTV camera by alerting types of violence, fall, and suicide attempts and minimizing the damage caused by that.")
    st.header('Sleep Lab Classification')
    st.write("Our sleep lab classification system is a tool that detects sleep apnea events using a microphone sound.")
    st.header('Pathology Slide Classification')
    st.write("Pathology slide classification system is a tool that classify Whole-slide Image (WSI) into 7 different cancer classes.")
    st.header('Covid-19 Outbreak Prediction in Thailand')
    st.write('We develop the system that can predict the number of Covid-19 patients during crisis in Thailand.')
    st.header('eKYC - Facial Recognition')
    st.write('eKYC and facial recognition are our services that prove patient by comparing faces on national ID card and selfie photo.')
