import streamlit as st
import streamlit.components.v1 as components
def app():
    st.title("List of EVER-AI Products")
    st.header("Health Dashboard")
    st.write("A Health dashboard is a tool that provides a centralized, interactive means of monitoring, measuring, analyzing, and extracting relevant health information insights from different hospital data warehouses while displaying information in an interactive, intuitive, and visual way")
    st.header("Predictive Health")
    st.write("Predictive health is a forecasting tool to identify patients who may be at high risk for hospitalization and diseases tiseases that could develop in the future.")
    st.header("Diagnosis Prediction based on Clinical Text")
    st.write("The goal of this tool is a model that estimates the probability of developing different diseases from patient symptom data using the LDA model, which is a probabilistic topic modeling technique that uses probability to assess and analyze the risk of different diseases arising from symptoms. Symptoms are recognizable or recurring patterns that are simple to identify.")
    st.header("Drug Recommendation System")
    st.write()
    st.header('Drug Interaction')
    st.write("Drug Interaction system to identify which drug interactions patients should avoid.")
    st.header('Outbreak Forecasting')
    st.write("Forecasting respiratory infectious disease outbreaks using Facebook's Prophet")
    st.header('Outbreak Map')
    st.write("Visualize the outbreak of respiratory infections on the map.")
    st.header('Parkinson Drawing Prediction')
    st.write("Parkinson Drawing Prediction to classify a person as Healthy or having Parkinson’s disease by looking at the Spiral Drawing made by the person")
    st.header('OCR (Image / Handwriting to Text)')
    st.write("Optical Character Recognition (OCR) tools that allows to convert National ID Card and Hospital Patient Registration Form images to text.")
    st.header('Speech Recognition')
    st.write("Text to speech (TTS) is a natural language modeling process that requires changing units of text into units of speech for audio presentation.")
    st.header('Chest X-ray Classification')
    st.write("Chest X-ray Classification to classify chest X-ray images into 12 different classes.")
    st.header('CCTV Detection')
    st.write("We are aiming to detect such types of violence, falling, and suicide from CCTV cameras to minimize the damage caused by that.")
    st.header('Sleep Lab Classification')
    st.write("A Sleep Lab Classification is a tool that detects sleep apnea events using a microphone sound.")
    st.header('Pathology Slide Classification')
    st.write("Pathology Slide Classification is a tool that classify Whole-slide Image (WSI) into 7 different cancer classes.")
    st.header('Covid-19 Outbreak Prediction in Thailand')
    st.write('Covid-19 Outbreak Prediction in Thailand')
    st.header('eKYC - Facial Recognition')
    st.write('Recognize and compare faces on national identification cards and selfie pictures.')